---
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - '**/*.erb'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'examples/**/*'
    - 'lib/vanagon/platform/defaults/*'

Gemspec/RequiredRubyVersion:
  Enabled: false

Lint/ElseLayout:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

# MAYBE useful - no return inside ensure block.
Lint/EnsureReturn:
  Enabled: true

# MAYBE useful - errors when rescue {} happens.
Lint/SuppressedException:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

# Can catch complicated strings.
Lint/LiteralInInterpolation:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2

# DISABLED really useless. Detects return as last statement.
Style/RedundantReturn:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: true

# DISABLED since for all the checked, we are basically checking nil
# TODO: Change the checking so that if the variable being assigned to has
# a value ALREADY, then raise an error.
Lint/AssignmentInCondition:
  Enabled: false

# DISABLED - not useful
Layout/SpaceBeforeComment:
  Enabled: false

# DISABLED - not useful
Style/HashSyntax:
  Enabled: false

# USES: as shortcut for non nil&valid checking a = x() and a.empty?
# DISABLED - not useful
Style/AndOr:
  Enabled: false

# DISABLED - not useful
Style/RedundantSelf:
  Enabled: false

# DISABLED - not useful
Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/VariableNumber:
  Enabled: false


# DISABLED - not useful
Style/WhileUntilModifier:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

# DISABLED - the offender is just haskell envy
Lint/AmbiguousRegexpLiteral:
  Enabled: false

Security/Eval:
  Enabled: true

# DISABLED
Layout/BlockAlignment:
  Enabled: false

# DISABLED
Layout/DefEndAlignment:
  Enabled: false

# DISABLED
Layout/EndAlignment:
  Enabled: false

# DISABLED
Layout/ConditionPosition:
  Enabled: false

# DISABLED
Layout/EmptyLineAfterGuardClause:
  Enabled: false

# DISABLED
Lint/DeprecatedClassMethods:
  Enabled: false

# DISABLED
Lint/Loop:
  Enabled: false

# DISABLED
Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Lint/RescueException:
  Enabled: false

Lint/RedundantStringCoercion:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/Void:
  Enabled: true

Layout/AccessModifierIndentation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/Alias:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Attr:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Style/CharacterLiteral:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/RedundantCondition:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/ClassMethods:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/WhenThen:
  Enabled: false

# DISABLED - not useful
Style/WordArray:
  Enabled: false

Style/RedundantPercentQ:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/IndentationStyle:
  Enabled: false

Layout/SpaceBeforeSemicolon:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceAfterMethodName:
  Enabled: true

Layout/SpaceAfterNot:
  Enabled: true

Layout/SpaceAfterSemicolon:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceBeforeComma:
  Enabled: true

Style/CollectionMethods:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Layout/DotPosition:
  Enabled: false

# DISABLED - used for converting to bool
Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/LineEndConcatenation:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: true

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineIfThen:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/NegatedWhile:
  Enabled: true

Style/Next:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/UnlessElse:
  Enabled: true

Style/VariableInterpolation:
  Enabled: true

Style/WhileUntilDo:
  Enabled: true

Style/EvenOdd:
  Enabled: true

Style/For:
  Enabled: true

Style/Lambda:
  Enabled: false

Naming/MethodName:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: true

Style/NestedTernaryOperator:
  Enabled: true

Style/NilComparison:
  Enabled: true

Style/FormatString:
  Enabled: true

Style/MultilineBlockChain:
  Enabled: true

Style/Semicolon:
  Enabled: true

Style/SignalException:
  Enabled: false

Style/NonNilCheck:
  Enabled: true

Style/Not:
  Enabled: true

Style/NumericLiterals:
  Enabled: true

Style/OneLineConditional:
  Enabled: true

Naming/BinaryOperatorParameterName:
  Enabled: true

Style/ParenthesesAroundCondition:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: true

Style/PerlBackrefs:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/RedundantException:
  Enabled: true

Style/SelfAssignment:
  Enabled: true

Style/Proc:
  Enabled: true

Style/RaiseArgs:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RescueModifier:
  Enabled: true

Style/RegexpLiteral:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: true

Metrics/ParameterLists:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Style/ModuleFunction:
  Enabled: false

Lint/Debugger:
  Enabled: false

Style/IfWithSemicolon:
  Enabled: true

Style/Encoding:
  Enabled: false

Style/CommandLiteral:
  EnforcedStyle: percent_x

# We have a few modules that are much larger than the default limit even when
# we don't count the comments. This isn't worth it to keep enabled.
Metrics/ModuleLength:
  Enabled: false

# I have no idea why, but it's complaining that we aren't using octal notation
# correctly when specifying file permissions. I have no idea how to resolve the
# complaint without disabling this cop. File permissions are not defined with
# octal notation. The complaint makes no sense.
Style/NumericLiteralPrefix:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false
