language: ruby
script: "bundle exec $CHECK"
sudo: false
notifications:
  email: false
rvm:
  - 2.5.1
  - 2.6.5
  - 2.7.2

env:
  - "CHECK='rspec spec --color --format documentation --order random'"
  - "CHECK='rubocop -D'"

matrix:
  exclude:
    - rvm: 2.6.5
      env: "CHECK='rubocop -D'"
